package services

// piecesindex.go loads the Activepieces piece index (packages/nodes/pieces/
// index.json, generated by apps/pieces-worker `npm run gen:index`) and merges
// each piece into the node catalog as its own cluster, so the map-reduce prompt
// compiler plans `pieces.<slug>.<action>` types exactly like hand-written
// catalog nodes. Execution is the reasoner's business: every run executes on the
// Temporal engine, whose DynamicWorkflow forwards `pieces.*` nodes to the Node
// pieces worker (docs/pieces-runtime-contract.md).
//
// A missing or malformed index is never an error — the platform degrades to the
// hand-written catalog, mirroring loadCatalogFrom's tolerance.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// pieceIndexFile mirrors the contract §2 schema.
type pieceIndexFile struct {
	Version int              `json:"version"`
	Nodes   []pieceIndexNode `json:"nodes"`
}

type pieceIndexNode struct {
	ID           string       `json:"id"`
	Piece        string       `json:"piece"`
	PieceVersion string       `json:"pieceVersion"`
	Action       string       `json:"action"`
	Label        string       `json:"label"`
	Description  string       `json:"description"`
	Kind         string       `json:"kind"`
	Search       []string     `json:"search"`
	Auth         *pieceAuth   `json:"auth"`
	Props        []pieceProp  `json:"props"`
}

type pieceAuth struct {
	Type          string `json:"type"`
	CredentialKey string `json:"credentialKey"`
	Required      bool   `json:"required"`
}

type pieceProp struct {
	Key         string `json:"key"`
	Label       string `json:"label"`
	Type        string `json:"type"`
	Required    bool   `json:"required"`
	Description string `json:"description"`
	Dynamic     bool   `json:"dynamic"`
}

// piecesIndexPath resolves the index location: PIECES_INDEX_PATH wins; otherwise
// walk up from the working directory (same discipline as catalogDir).
func piecesIndexPath() string {
	if v := os.Getenv("PIECES_INDEX_PATH"); v != "" {
		return v
	}
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for i := 0; i < 8; i++ {
		cand := filepath.Join(dir, "packages", "nodes", "pieces", "index.json")
		if st, err := os.Stat(cand); err == nil && !st.IsDir() {
			return cand
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return ""
}

// mergePiecesIndex loads the index at path and adds one cluster per piece to the
// catalog. Nil-safe and silent on any failure: prompt compilation must work with
// zero pieces exactly as it did before pieces existed.
func mergePiecesIndex(cat *Catalog, path string) {
	if cat == nil || path == "" {
		return
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var idx pieceIndexFile
	if err := json.Unmarshal(raw, &idx); err != nil {
		return
	}
	byCluster := map[string][]CatalogNode{}
	for _, n := range idx.Nodes {
		if n.ID == "" || !strings.HasPrefix(n.ID, "pieces.") {
			continue
		}
		slug := pieceSlugOf(n.ID)
		if slug == "" {
			continue
		}
		cluster := "pieces." + slug
		node := CatalogNode{
			ID:          n.ID,
			Label:       n.Label,
			Description: n.Description,
			Kind:        orStr(n.Kind, "action"),
			Runtime:     "piece", // executed on the Node pieces worker, opaque here
			Search:      strings.Join(n.Search, " "),
			Config:      piecePropsToFields(n.Props),
			Cluster:     cluster,
		}
		if n.Auth != nil && n.Auth.Type != "" && n.Auth.Type != "none" && n.Auth.CredentialKey != "" {
			node.Credentials = []CatalogCredential{{
				Key:  n.Auth.CredentialKey,
				Help: n.Auth.Type + " credential for the " + slug + " piece",
			}}
		}
		byCluster[cluster] = append(byCluster[cluster], node)
		cat.ByID[n.ID] = node
	}
	for cluster, nodes := range byCluster {
		slug := strings.TrimPrefix(cluster, "pieces.")
		cat.Clusters[cluster] = catalogFile{
			Cluster:     cluster,
			Label:       pieceDisplayName(slug) + " (Activepieces)",
			Description: "Actions from the " + pieceDisplayName(slug) + " Activepieces piece, executed on the pieces worker.",
			Nodes:       nodes,
		}
	}
}

// pieceSlugOf extracts <slug> from "pieces.<slug>.<action>".
func pieceSlugOf(id string) string {
	parts := strings.SplitN(id, ".", 3)
	if len(parts) != 3 || parts[0] != "pieces" {
		return ""
	}
	return parts[1]
}

// pieceDisplayName renders a slug as a human label: "google-sheets" → "Google Sheets".
func pieceDisplayName(slug string) string {
	words := strings.Split(slug, "-")
	for i, w := range words {
		if w != "" {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

// piecePropsToFields maps contract prop types onto the catalog's control
// vocabulary (the inspector's rendering hints — best-effort, text is the floor).
func piecePropsToFields(props []pieceProp) []CatalogField {
	fields := make([]CatalogField, 0, len(props))
	for _, p := range props {
		control := "text"
		switch p.Type {
		case "long_text", "json", "array", "object":
			control = "textarea"
		}
		help := p.Description
		if p.Dynamic {
			// Dropdown/dynamic props resolve options against the live service in
			// Activepieces' UI; here the planner supplies a plain value.
			help = strings.TrimSpace(help + " (dynamic in Activepieces — set a literal value)")
		}
		fields = append(fields, CatalogField{
			Key:      p.Key,
			Label:    orStr(p.Label, p.Key),
			Control:  control,
			Required: p.Required,
			Help:     help,
		})
	}
	return fields
}

func orStr(v, fallback string) string {
	if strings.TrimSpace(v) != "" {
		return v
	}
	return fallback
}
