package services

// piecesembed.go is the RECALL layer in front of the piece router: an offline
// embedding index over every piece action/trigger (packages/nodes/pieces/
// embeddings.json + embeddings.bin, generated by apps/pieces-worker
// `npm run gen:embeddings`), scored against the prompt's embedding at plan
// time. A piece's score is its BEST-matching single action (max, not sum —
// summing would favor big pieces for having more text, the exact bias the
// lexical prescreen suffered from).
//
// At ~7k vectors the scan is brute-force in memory: no vector store, a few
// milliseconds. Everything degrades silently — no sidecar, no Gemini key, or
// an embed-call failure just means the router reads the full directory.

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

const embedTimeout = 8 * time.Second

func embedModel() string { return envOr("PLANNER_EMBED_MODEL", "gemini-embedding-001") }

// pieceEmbeddings is the loaded sidecar: ids[i]'s unit-normalized vector is
// vecs[i*dims : (i+1)*dims].
type pieceEmbeddings struct {
	Model string
	Dims  int
	IDs   []string
	Vecs  []float32
}

// embeddingsManifest mirrors the generator's embeddings.json. Hashes (used by
// the generator for incremental rebuilds) are ignored here.
type embeddingsManifest struct {
	Version int      `json:"version"`
	Model   string   `json:"model"`
	Dims    int      `json:"dims"`
	IDs     []string `json:"ids"`
}

var (
	pieceEmbOnce sync.Once
	pieceEmbVal  *pieceEmbeddings
)

// loadPieceEmbeddings loads the sidecar once per process; nil means "not
// available" and is a valid steady state, never an error.
func loadPieceEmbeddings() *pieceEmbeddings {
	pieceEmbOnce.Do(func() {
		pieceEmbVal = loadPieceEmbeddingsFrom(piecesEmbeddingsPath())
	})
	return pieceEmbVal
}

// piecesEmbeddingsPath resolves the manifest location: PIECES_EMBEDDINGS_PATH
// wins; otherwise next to the pieces index (same walk-up discipline).
func piecesEmbeddingsPath() string {
	if v := os.Getenv("PIECES_EMBEDDINGS_PATH"); v != "" {
		return v
	}
	if idx := piecesIndexPath(); idx != "" {
		return filepath.Join(filepath.Dir(idx), "embeddings.json")
	}
	return ""
}

// loadPieceEmbeddingsFrom reads manifest + .bin (same basename). Any
// inconsistency — missing files, dims/count mismatch — returns nil.
func loadPieceEmbeddingsFrom(manifestPath string) *pieceEmbeddings {
	if manifestPath == "" {
		return nil
	}
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil
	}
	var m embeddingsManifest
	if err := json.Unmarshal(raw, &m); err != nil || m.Dims <= 0 || len(m.IDs) == 0 {
		return nil
	}
	binPath := strings.TrimSuffix(manifestPath, filepath.Ext(manifestPath)) + ".bin"
	data, err := os.ReadFile(binPath)
	if err != nil || len(data) != len(m.IDs)*m.Dims*4 {
		return nil
	}
	vecs := make([]float32, len(m.IDs)*m.Dims)
	for i := range vecs {
		vecs[i] = math.Float32frombits(binary.LittleEndian.Uint32(data[i*4:]))
	}
	return &pieceEmbeddings{Model: m.Model, Dims: m.Dims, IDs: m.IDs, Vecs: vecs}
}

// prefilterPieceClusters returns cluster keys ranked by their best action's
// similarity to the prompt, best first — roughly topN of them (score ties at
// the boundary are all kept, and clusters absent from the sidecar are appended
// unranked; see rankPieceClusters). ok=false means the prefilter is
// unavailable (no sidecar, no key, embed failure) and the caller should
// proceed with the full set.
func prefilterPieceClusters(ctx context.Context, cat *Catalog, prompt string, pieceKeys []string, topN int) ([]string, bool) {
	emb := loadPieceEmbeddings()
	if emb == nil {
		return nil, false
	}
	key := envOr("GEMINI_API_KEY", os.Getenv("GOOGLE_API_KEY"))
	if key == "" {
		return nil, false
	}
	qv, err := embedQueryGemini(ctx, key, orStr(emb.Model, embedModel()), emb.Dims, prompt)
	if err != nil {
		return nil, false
	}
	return rankPieceClusters(cat, emb, qv, pieceKeys, topN), true
}

// rankPieceClusters is the pure scoring core (separated for tests): dot every
// node vector against the query, roll up to clusters by max, rank descending.
// Alphabetical order among equal scores keeps the ORDER deterministic but may
// never decide SURVIVAL: the topN cut extends to include every cluster tied
// with the score at the boundary (asked for 100, ranks 99–102 tied → all 102).
// Clusters with no vector in the sidecar can't be judged at all, so they are
// appended after the ranked ones instead of silently vanishing — the prefilter
// is a recall layer; precision is the router's job.
func rankPieceClusters(cat *Catalog, emb *pieceEmbeddings, query []float32, pieceKeys []string, topN int) []string {
	allowed := make(map[string]bool, len(pieceKeys))
	for _, k := range pieceKeys {
		allowed[k] = true
	}
	best := map[string]float32{}
	for i, id := range emb.IDs {
		n, ok := cat.ByID[id]
		if !ok || !allowed[n.Cluster] {
			continue
		}
		var dot float32
		vec := emb.Vecs[i*emb.Dims : (i+1)*emb.Dims]
		for j, q := range query {
			dot += q * vec[j]
		}
		if cur, ok := best[n.Cluster]; !ok || dot > cur {
			best[n.Cluster] = dot
		}
	}
	ranked := make([]string, 0, len(best))
	for k := range best {
		ranked = append(ranked, k)
	}
	sort.Slice(ranked, func(i, j int) bool {
		if best[ranked[i]] != best[ranked[j]] {
			return best[ranked[i]] > best[ranked[j]]
		}
		return ranked[i] < ranked[j]
	})
	if len(ranked) > topN {
		cut := topN
		for cut < len(ranked) && best[ranked[cut]] == best[ranked[topN-1]] {
			cut++
		}
		ranked = ranked[:cut]
	}
	var unscored []string
	for _, k := range pieceKeys {
		if _, ok := best[k]; !ok {
			unscored = append(unscored, k)
		}
	}
	sort.Strings(unscored)
	return append(ranked, unscored...)
}

// embedQueryGemini embeds one query text (taskType RETRIEVAL_QUERY, matching
// the sidecar's RETRIEVAL_DOCUMENT side) and unit-normalizes the result —
// Gemini embeddings below 3072 dims are not pre-normalized, and normalized
// vectors make dot product equal cosine similarity.
func embedQueryGemini(ctx context.Context, key, model string, dims int, text string) ([]float32, error) {
	ctx, cancel := context.WithTimeout(ctx, embedTimeout)
	defer cancel()
	body, _ := json.Marshal(map[string]any{
		"model":                "models/" + model,
		"content":              map[string]any{"parts": []map[string]string{{"text": text}}},
		"taskType":             "RETRIEVAL_QUERY",
		"outputDimensionality": dims,
	})
	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:embedContent", model)
	req, _ := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	req.Header.Set("content-type", "application/json")
	req.Header.Set("x-goog-api-key", key)
	resp, err := (&http.Client{Timeout: embedTimeout}).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("gemini embed status %d", resp.StatusCode)
	}
	var parsed struct {
		Embedding struct {
			Values []float32 `json:"values"`
		} `json:"embedding"`
	}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return nil, err
	}
	v := parsed.Embedding.Values
	if len(v) != dims {
		return nil, fmt.Errorf("gemini embed: got %d dims, want %d", len(v), dims)
	}
	var norm float64
	for _, x := range v {
		norm += float64(x) * float64(x)
	}
	if norm == 0 {
		return nil, fmt.Errorf("gemini embed: zero vector")
	}
	scale := float32(1 / math.Sqrt(norm))
	for i := range v {
		v[i] *= scale
	}
	return v, nil
}
