package services

// piecesembed.go is the RECALL layer in front of the piece router: an offline
// embedding index over every piece action/trigger (packages/nodes/pieces/
// embeddings.json + embeddings.bin, generated by apps/pieces-worker
// `npm run gen:embeddings`), scored against the prompt's embedding at plan
// time. A piece's score is its BEST-matching single action (max, not sum —
// summing would favor big pieces for having more text, the exact bias the
// lexical prescreen suffered from).
//
// At ~7k vectors the scan is brute-force in memory: no vector store, a few
// milliseconds. Nothing here degrades any more: a missing sidecar, a missing
// VOYAGE_API_KEY, a sidecar built with a different model or dimension, or a
// failed embed call are all ERRORS. A stale sidecar quietly scoring a prompt
// against vectors from another model is precisely the kind of invisible wrong
// answer this codebase is being cured of.
//
// Embeddings are Voyage. Anthropic publishes no embeddings endpoint, which is
// why this is the one place a second credential is unavoidable.

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const embedTimeout = 8 * time.Second

const voyageEmbeddingsURL = "https://api.voyageai.com/v1/embeddings"

// Voyage's current line is voyage-4{,-lite,-large}; the 3.x family is legacy.
// Supported widths are 2048/1024/512/256 — note 768 (the width of the original
// Gemini-era sidecar) is NOT among them, so a pre-Voyage sidecar can never match.
func embedModel() string { return envOr("PLANNER_EMBED_MODEL", "voyage-4") }

// RequireVoyageKey is the boot preflight for the embedding prefilter.
func RequireVoyageKey() error {
	if strings.TrimSpace(os.Getenv("VOYAGE_API_KEY")) == "" {
		return errors.New("VOYAGE_API_KEY is required — the piece router prefilters ~700 " +
			"clusters through the embedding sidecar, and Anthropic publishes no embeddings " +
			"endpoint. Set it in .env")
	}
	return nil
}

func embedDims() int {
	if n, err := strconv.Atoi(envOr("PLANNER_EMBED_DIMS", "1024")); err == nil && n > 0 {
		return n
	}
	return 1024
}

// RequirePieceEmbeddings is the boot preflight for the sidecar itself: present,
// readable, and built with the model and width this process is configured for.
func RequirePieceEmbeddings() error {
	emb, err := loadPieceEmbeddings()
	if err != nil {
		return err
	}
	return checkSidecarMatches(emb)
}

// checkSidecarMatches rejects a sidecar built by a different model or at a
// different width — its vectors are not comparable with the query vectors this
// process will produce, so scoring them would be meaningless rather than merely
// degraded.
func checkSidecarMatches(emb *pieceEmbeddings) error {
	if emb.Model != embedModel() || emb.Dims != embedDims() {
		return fmt.Errorf("piece embedding sidecar is stale: built with model %q at %d dims, "+
			"but this process is configured for %q at %d dims. Rebuild it: "+
			"cd apps/pieces-worker && npm run gen:embeddings",
			emb.Model, emb.Dims, embedModel(), embedDims())
	}
	return nil
}

// pieceEmbeddings is the loaded sidecar: ids[i]'s unit-normalized vector is
// vecs[i*dims : (i+1)*dims].
type pieceEmbeddings struct {
	Model string
	Dims  int
	IDs   []string
	Vecs  []float32
}

// embeddingsManifest mirrors the generator's embeddings.json. Hashes (used by
// the generator for incremental rebuilds) are ignored here.
type embeddingsManifest struct {
	Version int      `json:"version"`
	Model   string   `json:"model"`
	Dims    int      `json:"dims"`
	IDs     []string `json:"ids"`
}

var (
	pieceEmbOnce sync.Once
	pieceEmbVal  *pieceEmbeddings
	pieceEmbErr  error
)

// loadPieceEmbeddings loads the sidecar once per process. Absence is no longer a
// valid steady state — the router depends on it, so it is an error.
func loadPieceEmbeddings() (*pieceEmbeddings, error) {
	pieceEmbOnce.Do(func() {
		pieceEmbVal, pieceEmbErr = loadPieceEmbeddingsFrom(piecesEmbeddingsPath())
	})
	return pieceEmbVal, pieceEmbErr
}

// piecesEmbeddingsPath resolves the manifest location: PIECES_EMBEDDINGS_PATH
// wins; otherwise next to the pieces index (same walk-up discipline).
func piecesEmbeddingsPath() string {
	if v := os.Getenv("PIECES_EMBEDDINGS_PATH"); v != "" {
		return v
	}
	if idx := piecesIndexPath(); idx != "" {
		return filepath.Join(filepath.Dir(idx), "embeddings.json")
	}
	return ""
}

// loadPieceEmbeddingsFrom reads manifest + .bin (same basename). Every
// inconsistency — missing files, unparseable manifest, size mismatch — names
// itself, because each has a different fix.
func loadPieceEmbeddingsFrom(manifestPath string) (*pieceEmbeddings, error) {
	const rebuild = "rebuild it: cd apps/pieces-worker && npm run gen:embeddings"
	if manifestPath == "" {
		return nil, fmt.Errorf("piece embedding sidecar not found: no pieces index to sit beside " +
			"and PIECES_EMBEDDINGS_PATH unset")
	}
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("piece embedding sidecar %s: %w — %s", manifestPath, err, rebuild)
	}
	var m embeddingsManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("piece embedding sidecar %s is not valid JSON: %w — %s", manifestPath, err, rebuild)
	}
	if m.Dims <= 0 || len(m.IDs) == 0 {
		return nil, fmt.Errorf("piece embedding sidecar %s is empty (%d ids, %d dims) — %s",
			manifestPath, len(m.IDs), m.Dims, rebuild)
	}
	binPath := strings.TrimSuffix(manifestPath, filepath.Ext(manifestPath)) + ".bin"
	data, err := os.ReadFile(binPath)
	if err != nil {
		return nil, fmt.Errorf("piece embedding vectors %s: %w — %s", binPath, err, rebuild)
	}
	if want := len(m.IDs) * m.Dims * 4; len(data) != want {
		return nil, fmt.Errorf("piece embedding vectors %s: %d bytes, want %d (%d ids × %d dims) — %s",
			binPath, len(data), want, len(m.IDs), m.Dims, rebuild)
	}
	vecs := make([]float32, len(m.IDs)*m.Dims)
	for i := range vecs {
		vecs[i] = math.Float32frombits(binary.LittleEndian.Uint32(data[i*4:]))
	}
	return &pieceEmbeddings{Model: m.Model, Dims: m.Dims, IDs: m.IDs, Vecs: vecs}, nil
}

// prefilterPieceClusters returns cluster keys ranked by their best action's
// similarity to the prompt, best first — roughly topN of them (score ties at
// the boundary are all kept, and clusters absent from the sidecar are appended
// unranked; see rankPieceClusters).
func prefilterPieceClusters(ctx context.Context, cat *Catalog, prompt string, pieceKeys []string, topN int) ([]string, error) {
	emb, err := loadPieceEmbeddings()
	if err != nil {
		return nil, err
	}
	if err := checkSidecarMatches(emb); err != nil {
		return nil, err
	}
	if err := RequireVoyageKey(); err != nil {
		return nil, err
	}
	qv, err := embedQueryVoyage(ctx, os.Getenv("VOYAGE_API_KEY"), emb.Model, emb.Dims, prompt)
	if err != nil {
		return nil, err
	}
	return rankPieceClusters(cat, emb, qv, pieceKeys, topN), nil
}

// rankPieceClusters is the pure scoring core (separated for tests): dot every
// node vector against the query, roll up to clusters by max, rank descending.
// Alphabetical order among equal scores keeps the ORDER deterministic but may
// never decide SURVIVAL: the topN cut extends to include every cluster tied
// with the score at the boundary (asked for 100, ranks 99–102 tied → all 102).
// Clusters with no vector in the sidecar can't be judged at all, so they are
// appended after the ranked ones instead of silently vanishing — the prefilter
// is a recall layer; precision is the router's job.
func rankPieceClusters(cat *Catalog, emb *pieceEmbeddings, query []float32, pieceKeys []string, topN int) []string {
	allowed := make(map[string]bool, len(pieceKeys))
	for _, k := range pieceKeys {
		allowed[k] = true
	}
	best := map[string]float32{}
	for i, id := range emb.IDs {
		n, ok := cat.ByID[id]
		if !ok || !allowed[n.Cluster] {
			continue
		}
		var dot float32
		vec := emb.Vecs[i*emb.Dims : (i+1)*emb.Dims]
		for j, q := range query {
			dot += q * vec[j]
		}
		if cur, ok := best[n.Cluster]; !ok || dot > cur {
			best[n.Cluster] = dot
		}
	}
	ranked := make([]string, 0, len(best))
	for k := range best {
		ranked = append(ranked, k)
	}
	sort.Slice(ranked, func(i, j int) bool {
		if best[ranked[i]] != best[ranked[j]] {
			return best[ranked[i]] > best[ranked[j]]
		}
		return ranked[i] < ranked[j]
	})
	if len(ranked) > topN {
		cut := topN
		for cut < len(ranked) && best[ranked[cut]] == best[ranked[topN-1]] {
			cut++
		}
		ranked = ranked[:cut]
	}
	var unscored []string
	for _, k := range pieceKeys {
		if _, ok := best[k]; !ok {
			unscored = append(unscored, k)
		}
	}
	sort.Strings(unscored)
	return append(ranked, unscored...)
}

// embedQueryVoyage embeds one query text and unit-normalizes the result, so the
// dot product in rankPieceClusters equals cosine similarity.
//
// input_type matters and must mirror the generator: Voyage prepends a different
// instruction for "query" than for "document", and the sidecar is built with
// "document". Getting this backwards costs recall silently, which is why both
// sides name it explicitly rather than relying on the default.
func embedQueryVoyage(ctx context.Context, key, model string, dims int, text string) ([]float32, error) {
	ctx, cancel := context.WithTimeout(ctx, embedTimeout)
	defer cancel()
	body, _ := json.Marshal(map[string]any{
		"model":            model,
		"input":            []string{text},
		"input_type":       "query",
		"output_dimension": dims,
	})
	req, _ := http.NewRequestWithContext(ctx, http.MethodPost, voyageEmbeddingsURL, bytes.NewReader(body))
	req.Header.Set("content-type", "application/json")
	req.Header.Set("authorization", "Bearer "+key)
	resp, err := (&http.Client{Timeout: embedTimeout}).Do(req)
	if err != nil {
		return nil, fmt.Errorf("voyage embed: %w", err)
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("voyage embed status %d: %s", resp.StatusCode, truncateStr(string(raw), 300))
	}
	var parsed struct {
		Data []struct {
			Embedding []float32 `json:"embedding"`
		} `json:"data"`
	}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		return nil, fmt.Errorf("voyage embed: unparseable response: %w", err)
	}
	if len(parsed.Data) == 0 {
		return nil, fmt.Errorf("voyage embed: no embeddings returned")
	}
	v := parsed.Data[0].Embedding
	if len(v) != dims {
		return nil, fmt.Errorf("voyage embed: got %d dims, want %d", len(v), dims)
	}
	var norm float64
	for _, x := range v {
		norm += float64(x) * float64(x)
	}
	if norm == 0 {
		return nil, fmt.Errorf("voyage embed: zero vector")
	}
	scale := float32(1 / math.Sqrt(norm))
	for i := range v {
		v[i] *= scale
	}
	return v, nil
}
