#!/usr/bin/env node
// Regenerate the web palette's view of the integration catalog AND the
// credential-types catalog (docs/credentials-contract.md §§1-3):
//
//   node packages/nodes/build-web.mjs
//
// Inputs:
//   catalog/*.json          — hand-written clusters (builtin excluded: those stay
//                             hand-defined in node-catalog.ts with their icons)
//   pieces/index.json       — Activepieces action index, generated by
//                             apps/pieces-worker `npm run gen:index`
//
// Outputs (the ONLY writer of both — the web app never edits them):
//   apps/web/components/builder/integration-catalog.generated.json
//   apps/web/components/builder/credential-types.generated.json
//
// Run after editing any cluster file or regenerating the pieces index; commit
// the outputs.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const catalogDir = join(here, "catalog");
const piecesIndexFile = join(here, "pieces", "index.json");
const webBuilderDir = join(here, "..", "..", "apps", "web", "components", "builder");
const catalogOut = join(webBuilderDir, "integration-catalog.generated.json");
const credTypesOut = join(webBuilderDir, "credential-types.generated.json");

/* ------------------------------ small helpers ------------------------------ */

// "SLACK_BOT_TOKEN" → "Slack Bot Token" (§3 field-label rule for env keys).
function titleCaseEnvKey(key) {
  return key
    .split("_")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

// "sales-and-crm" / "SALES_AND_CRM" → "Sales and CRM"-style human label.
const LABEL_SPECIAL = { and: "and", or: "or", of: "of", crm: "CRM", ai: "AI", api: "API" };
function humanizeWords(raw) {
  return raw
    .toLowerCase()
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((w) => LABEL_SPECIAL[w] ?? w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

/* ----------------------- §1 prop-type → control mapping ---------------------- */

// Maps one Activepieces index prop onto the shared field vocabulary. Returns
// null when the prop must be omitted (markdown = display-only).
function pieceFieldFor(p) {
  const field = { key: p.key, label: p.label || p.key };
  if (p.required) field.required = true;
  let help = p.description || "";

  switch (p.type) {
    case "short_text":
      field.control = "text";
      break;
    case "long_text":
      field.control = "textarea";
      break;
    case "number":
      field.control = "number";
      break;
    case "checkbox":
      field.control = "checkbox";
      break;
    case "secret_text":
      field.control = "secret";
      break;
    case "json":
    case "object":
    case "array":
      field.control = "json";
      break;
    case "date_time":
      field.control = "text";
      help = [help, "ISO 8601 timestamp, e.g. 2026-01-31T09:00:00Z"].filter(Boolean).join(" — ");
      break;
    case "file":
      field.control = "text";
      help = [help, "Enter a URL to the file"].filter(Boolean).join(" — ");
      break;
    case "markdown":
      return null; // display-only, omitted (§1)
    case "static_dropdown":
      if (p.options?.length) {
        field.control = "select";
        field.options = p.options;
        break;
      }
    // static_dropdown without scalar options degrades like a dynamic prop:
    // falls through to the raw-value text fallback.
    case "dropdown":
    case "multi_select_dropdown":
    case "static_multi_select_dropdown":
    case "dynamic":
      field.control = "text";
      field.dynamic = true;
      help = [help, "Options load dynamically in Activepieces — enter the raw value/ID directly"]
        .filter(Boolean)
        .join(" — ");
      break;
    default:
      field.control = "text";
  }
  if (help) field.help = help;
  return field;
}

/* -------------------- hand-written catalog → nodes + types ------------------- */

const nodes = [];
const credentialTypes = {};
// provider → { label, fields: Map<envKey, field> } accumulated across nodes.
const catalogProviders = new Map();

for (const name of readdirSync(catalogDir).sort()) {
  if (!name.endsWith(".json") || name === "builtin.json") continue;
  const file = JSON.parse(readFileSync(join(catalogDir, name), "utf8"));
  for (const n of file.nodes ?? []) {
    const credKeys = (n.credentials ?? []).map((c) => c.key);
    const provider = n.id.split(".")[0];
    const node = {
      id: n.id,
      label: n.label,
      description: n.description,
      kind: n.kind,
      runtime: n.runtime,
      cluster: file.cluster,
      clusterLabel: file.label ?? file.cluster,
      config: (n.config ?? []).map(({ key, label, control, required, placeholder, options, help }) => ({
        key, label, control,
        ...(required ? { required } : {}),
        ...(placeholder ? { placeholder } : {}),
        ...(options ? { options } : {}),
        ...(help ? { help } : {}),
      })),
      credentials: credKeys,
    };

    if (credKeys.length > 0) {
      // §3: credential type id = first id segment; label = the provider's
      // display name (the "Provider:" prefix every catalog node label carries).
      node.credentialType = provider;
      const labelPrefix = String(n.label ?? "").includes(":")
        ? String(n.label).split(":")[0].trim()
        : humanizeWords(provider);
      const meta = catalogProviders.get(provider) ?? { label: labelPrefix, fields: new Map() };
      for (const c of n.credentials) {
        const existing = meta.fields.get(c.key);
        if (!existing) {
          meta.fields.set(c.key, {
            key: c.key,
            label: titleCaseEnvKey(c.key),
            control: "secret",
            required: true,
            ...(c.help ? { help: c.help } : {}),
          });
        } else if (c.help && !existing.help) {
          existing.help = c.help; // first non-empty help wins
        }
      }
      catalogProviders.set(provider, meta);
    }
    nodes.push(node);
  }
}

for (const [provider, meta] of [...catalogProviders.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  credentialTypes[provider] = {
    id: provider,
    label: meta.label,
    source: "catalog",
    fields: [...meta.fields.values()],
  };
}
const catalogNodeCount = nodes.length;
const catalogTypeCount = Object.keys(credentialTypes).length;

/* ------------------------ pieces index → nodes + types ----------------------- */

// §3 credential fields per auth type. custom_auth props map via §1.
function pieceAuthFields(auth) {
  switch (auth.type) {
    case "secret_text":
      return [{
        key: "value",
        label: auth.displayName || "API Key",
        control: "secret",
        required: true,
        ...(auth.description ? { help: auth.description } : {}),
      }];
    case "basic_auth":
      return [
        { key: "username", label: "Username", control: "text", required: true },
        { key: "password", label: "Password", control: "secret", required: true },
      ];
    case "oauth2":
      // Manual token entry for now — no OAuth dance (§3).
      return [
        { key: "access_token", label: "Access Token", control: "secret", required: true },
        { key: "refresh_token", label: "Refresh Token", control: "secret", required: false },
      ];
    case "custom_auth":
      return (auth.props ?? [])
        .map((p) => pieceFieldFor({
          key: p.key,
          label: p.displayName || p.key,
          type: p.type,
          required: p.required,
          description: p.description,
        }))
        .filter(Boolean);
    default:
      return [];
  }
}

let piecesNodeCount = 0;
let piecesTypeCount = 0;
if (existsSync(piecesIndexFile)) {
  const idx = JSON.parse(readFileSync(piecesIndexFile, "utf8"));
  for (const n of idx.nodes ?? []) {
    const slug = n.id.split(".")[1] ?? "";
    if (!slug) continue;
    const category = (n.categories ?? [])[0] ?? "";
    const cluster = category ? category.toLowerCase().replace(/_/g, "-") : "pieces";
    const clusterLabel = category ? humanizeWords(category) : "Pieces";
    const hasAuth = Boolean(n.auth && n.auth.type && n.auth.type !== "none");
    const typeId = `pieces.${slug}`;

    // Triggers carry their framework strategy (webhook | polling | app_webhook)
    // so the builder can label them and the trigger enable/disable UI keys off
    // it (docs/pieces-runtime-contract.md §7a). Actions never have one.
    const isTrigger = n.kind === "trigger";
    nodes.push({
      id: n.id,
      label: n.label,
      description: n.description,
      kind: n.kind ?? "action",
      runtime: "pieces",
      cluster,
      clusterLabel,
      config: (n.props ?? []).map(pieceFieldFor).filter(Boolean),
      credentials: [],
      credentialType: hasAuth ? typeId : null,
      ...(isTrigger && n.strategy ? { strategy: n.strategy } : {}),
    });
    piecesNodeCount++;

    if (hasAuth && !credentialTypes[typeId]) {
      credentialTypes[typeId] = {
        id: typeId,
        label: n.pieceDisplayName || humanizeWords(slug),
        source: "pieces",
        authType: n.auth.type,
        fields: pieceAuthFields(n.auth),
      };
      piecesTypeCount++;
    }
  }
} else {
  console.warn(`pieces index not found at ${piecesIndexFile} — run apps/pieces-worker gen:index first; emitting catalog nodes only`);
}

/* ---------------------------------- write ---------------------------------- */

writeFileSync(catalogOut, JSON.stringify(nodes, null, 1) + "\n");
writeFileSync(credTypesOut, JSON.stringify(credentialTypes, null, 1) + "\n");
console.log(
  `wrote ${nodes.length} integration nodes (${catalogNodeCount} catalog + ${piecesNodeCount} pieces) → ${catalogOut}`,
);
console.log(
  `wrote ${Object.keys(credentialTypes).length} credential types (${catalogTypeCount} catalog + ${piecesTypeCount} pieces) → ${credTypesOut}`,
);
