"""Loader for the Activepieces piece index (packages/nodes/pieces/index.json).

The index is generated by apps/pieces-worker (`npm run gen:index`) from the
installed @activepieces/piece-* npm packages. Node types are namespaced
`pieces.<piece-slug>.<action-name>` (docs/pieces-runtime-contract.md §1-2).

Execution does NOT happen here: piece nodes run on the Node pieces worker via
the cross-queue `execute_piece` Temporal activity. This module only answers
"is this type a piece action, and what does it need?" for the Python-side
prepare/record activities.

Loaded once at import, like catalog.py. A missing or unreadable index IS an
error: it used to mean every pieces.* node quietly recorded intent under the
reason "unknown-piece", so a forgotten `npm run gen:index` looked identical to a
workflow that genuinely referenced a piece nobody installed.
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

log = logging.getLogger("reasoner.pieces")

# apps/reasoner/reasoner/pieces.py → repo root is three levels up.
_REPO_ROOT = Path(__file__).resolve().parents[3]

PIECE_PREFIX = "pieces."


def _index_path() -> Path | None:
    if env := os.getenv("PIECES_INDEX_PATH"):
        p = Path(env)
        return p if p.is_file() else None
    p = _REPO_ROOT / "packages" / "nodes" / "pieces" / "index.json"
    return p if p.is_file() else None


def _load() -> dict[str, dict[str, Any]]:
    by_id: dict[str, dict[str, Any]] = {}
    path = _index_path()
    if path is None:
        raise SystemExit(
            "Piece index not found — pieces.* nodes cannot be prepared without it. "
            "Generate it: cd apps/pieces-worker && npm run gen:index "
            "(or point PIECES_INDEX_PATH at an existing index.json)."
        )
    try:
        data = json.loads(path.read_text())
    except (OSError, ValueError) as exc:
        raise SystemExit(f"Piece index {path} is unreadable: {exc}") from exc
    for node in data.get("nodes", []):
        node_id = node.get("id")
        if node_id:
            by_id[node_id] = node
    log.info("pieces index loaded: %d actions", len(by_id))
    return by_id


_BY_ID = _load()


def is_piece_type(node_type: str) -> bool:
    """True for `pieces.<slug>.<action>` node types (contract §1)."""
    return node_type.startswith(PIECE_PREFIX)


def piece_spec_for(node_type: str) -> dict[str, Any] | None:
    """Full index entry for a piece node type, or None if unknown."""
    return _BY_ID.get(node_type)


def credential_key_for(spec: dict[str, Any]) -> str | None:
    """The AP_<SLUG>_AUTH env var a piece resolves, or None for auth-less pieces."""
    auth = spec.get("auth") or {}
    if not auth or auth.get("type") in ("", "none", None):
        return None
    return auth.get("credentialKey") or None


def auth_required(spec: dict[str, Any]) -> bool:
    auth = spec.get("auth") or {}
    return bool(auth.get("required")) and auth.get("type") not in ("", "none", None)


def size() -> int:
    return len(_BY_ID)
